import prism from 'prismjs'

import 'prismjs-components-importer/cjs/prism-c.js'
import 'prismjs-components-importer/cjs/prism-clojure.js'
import 'prismjs-components-importer/cjs/prism-cpp.js'
import 'prismjs-components-importer/cjs/prism-csharp.js'
import 'prismjs-components-importer/cjs/prism-css.js'
import 'prismjs-components-importer/cjs/prism-dart.js'
import 'prismjs-components-importer/cjs/prism-docker.js'
import 'prismjs-components-importer/cjs/prism-elixir.js'
import 'prismjs-components-importer/cjs/prism-go.js'
import 'prismjs-components-importer/cjs/prism-markup.js'
import 'prismjs-components-importer/cjs/prism-java.js'
import 'prismjs-components-importer/cjs/prism-javascript.js'
import 'prismjs-components-importer/cjs/prism-json.js'
import 'prismjs-components-importer/cjs/prism-julia.js'
import 'prismjs-components-importer/cjs/prism-kotlin.js'
import 'prismjs-components-importer/cjs/prism-lua.js'
import 'prismjs-components-importer/cjs/prism-markdown.js'
import 'prismjs-components-importer/cjs/prism-pascal.js'
import 'prismjs-components-importer/cjs/prism-php.js'
import 'prismjs-components-importer/cjs/prism-python.js'
import 'prismjs-components-importer/cjs/prism-ruby.js'
import 'prismjs-components-importer/cjs/prism-rust.js'
import 'prismjs-components-importer/cjs/prism-sql.js'
import 'prismjs-components-importer/cjs/prism-typescript.js'
import 'prismjs-components-importer/cjs/prism-yaml.js'

export default prism
